### PR TITLE
Report succesful tests and add failures to quickfix

### PR DESCRIPTION
**Pull request by mfussenegger**
Adresses parts of https://github.com/mfussenegger/nvim-jdtls/issues/31

https://user-images.githubusercontent.com/38700/108778296-703b1900-7565-11eb-8598-b952f229d301.mp4

### CODE REVIEW

**Comment by jlesquembre** [comment]
thanks @mfussenegger ! I tested it, looks better :-)  I see the test results in the dap-repl, but:
- In the terminal buffer I still only see the `[Process exited 0]` message
- No errors are loaded in the quickfix list, and I get the message `... All  10 succeeded `, but I can see the error in the dap-repl

It would be nice if we can reuse the same terminal to re-run the tests (or at least close automatically the previous terminal buffer) . It is a bit annoying to have a new window every time I run the tests.

In case is relevant, I tested it with jdk15 and Junit4

**Comment by mfussenegger** [comment]
> In the terminal buffer I still only see the [Process exited 0] message

This depends on the test case you're running. If it writes to stdout or stderr you should see some output in the terminal.


> No errors are loaded in the quickfix list, and I get the message ... All 10 succeeded , but I can see the error in the dap-repl


This is strange. What's the exact error that's written to the dap-repl, a stacktrace?


> It would be nice if we can reuse the same terminal to re-run the tests (or at least close automatically the previous terminal buffer) . It is a bit annoying to have a new window every time I run the tests.

Yes I was thinking the same. This will have to change in nvim-dap itself.

**Comment by jlesquembre** [comment]
> This depends on the test case you're running. If it writes to stdout or stderr you should see some output in the terminal.
I'll check it tomorrow, I'm not sure if the test writes to strout/stderr

> This is strange. What's the exact error that's written to the dap-repl, a stacktrace?
Yes, in dap-repl I see a stacktrace, the same I see if I run `mvn test`

**Comment by mfussenegger** [comment]
> Yes, in dap-repl I see a stacktrace, the same I see if I run mvn test

Could you post the stacktrace output?

There's some logic that tries to find the test class in the stacktrace to get the line number of the test case that triggered the error. If that doesn't exist it currently doesn't pop up in the quickfix list/is not counted.

**Comment by jlesquembre** [comment]
I debug it a bit, and has nothing to do with the class/method name. It only fails when I do the assert inside a `doOnSuccess` from RxJava. But not always. If a find an easy case to reproduce, I'll post it, but for now I don't want to spend more time on it, since seems a rare corner case

> This depends on the test case you're running. If it writes to stdout or stderr you should see some output in the terminal.

Right, if I do a `System.out.print`, it's showed in the terminal. I expected to see a similar output to the video you posted, but I guess that's an issue with my maven configuration

**Pull request merged**
