### PR TITLE
adjusted the interface of `jdtls.setup.start_or_attach`

### PR DESCRIPTION
**Pull request by bugabinga**
the function `start_or_attach` has the same interface as `vim.lsp.start`
now.

this helps to embed nvim-jdtls into nvim lua configurations, that wish
to abstract over multiple different LSPs.

### CODE REVIEW

**Comment by bugabinga** [comment]
Hm, should a third table be passed then?

**Comment by mfussenegger** [comment]
Could you explain the use-case a bit more? I'm not sure if the `opts` from vim.lsp.start make sense in this context.

**Comment by bugabinga** [comment]
I am configuring my LSPs similar to how nvim-lspconfig does it. There is a collection of declarative "config" tables that each describe some LSP. I want one of these LSPs to be jdtls, but managed by nvim-jdtls.

```lua
local jdtls_lsp_start = function(config, opts)
  require 'jdtls'.start_or_attach(config, opts)
end

return {
  custom_start = jdtls_lsp_start,
  name = 'jdtls_ss',
  filetypes = 'java',
  command = create_jdtls_command(true),
  root_dir = project.find_java_project_root,
  single_file_support = true,
  workspaces = false,
  settings = { java = java_settings },
}
```

Ultimately, the config tables essentially are what gets passed into `vim.lsp.start` as `config`.
```lua
    local lsp_starter = config.custom_start or vim.lsp.start

    lsp_starter( start_config, {
      bufnr = bufnr,
      reuse_client = function ( existing_client, config )
        return existing_client.name == config.name and existing_client.root_dir == config.root_dir;
      end,
    } )
```

Another possibility to achieve this might be to use the `before_init` function in `vim.lsp.start` `config`, like [neodev](https://github.com/folke/neodev.nvim#-setup) does it.
But I suspect the setup nvim-jdtls does is much more complicated than just augmenting the LSP settings.

**Comment by bugabinga** [comment]
Should I:
* add a third table to `start_or_attach` -> `require 'jdtls'.start_or_attach(config, opts, start_opts)`
* try to make `before_init` work
* close this PR and we just say: "nvim-jdtls is meant to take over lsp client init rather than be integrated in other lsp init configs"

I do not mind maintaining my own fork of `nivm-jdtls` since it is likely I am the only one with this esoteric requirement ;).

**Comment by mfussenegger** [comment]
Merged https://github.com/mfussenegger/nvim-jdtls/pull/578

**Pull request closed without merging**
