### PR TITLE
java_type_hierarchy: class, method type hierarchy on the quickfix list

### PR DESCRIPTION
**Pull request by lbrayner**
`java_type_hierarchy` uses `java.navigate.openTypeHierarchy` and `java.navigate.resolveTypeHierarchy` to show type hierarchy information of a class or method on the quickfix list.

### CODE REVIEW

**Comment by lbrayner** [comment]
Please consider adding something like this to nvim-jdtls.

**Comment by lbrayner** [comment]
The motivation for this was https://github.com/eclipse/eclipse.jdt.ls/issues/2684.

I was looking for a way to jump from an interface method implementation on a class to its declaration on the interface file. `java_type_hierarchy` also delivers that..

**Comment by mfussenegger** [comment]
Type hierarchy is also part of the spec: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareTypeHierarchy

I think eclipse.jdt.ls and neovim core should implement that instead of going with the custom off-spec variant

**Comment by mfussenegger** [comment]
See also https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2769

I'm not going to merge the off-spec variant. type hierarchy should be implemented in neovim core instead

**Pull request closed without merging**
