### PR TITLE
Retry calling setup_dap() if no configurations are found.

### PR DESCRIPTION
**Pull request by MrcJkb**
In some projects, eclipse jdt.ls may take longer to load the project than it takes to call `setup_dap()`. [See this nvim-dap issue.](https://github.com/mfussenegger/nvim-dap/issues/181)

This PR solves this problem by recursively retrying `setup_dap()` when `dap.continue()` is called and no java configurations are found.

### CODE REVIEW

**Review by mfussenegger — COMMENTED** [review]
Thank you for the contribution and for pointing out this problem.


I'm not really sure if this is a good way to solve this - but ad-hoc I also can't think of a better way.

`original_configurations` can't really be used as indication of whether mainclasses could be discovered or not, at least not in the form as it is in the PR.

`original_configurations` is the configuration that a user may have manually configured (or created via the `.vscode/launch.json` support).

This means it is possible for `original_configurations` to be non-empty and for the mainclass discovery to have failed. I guess this could be solved by introducing another internal flag. Some kind of `discovered_mainclasses` indication.


But the other problem is that without configurations, the adapter function won't be called. Even if it were - the newly discovered configurations would only be available for the next time a user invokes `.continue()`.


I'll let this sink in for a bit - maybe I'll have an idea how this could be solved in a better way. Ideally it would also manage to discover new main classes that are created after the setup.

That would either require `dap` to have a hook to load configurations ad-hoc, or nvim-jdtls would need to react to some jdt compile/status events? I'm not sure yet.

**Comment by theHamsta** [comment]
Would it be a problem to just always call `setup_dap` before you run a Java debug session and make `setup_dap` always ask the debug adapter for the main classes even if there are already debug configurations set (and just insert new configurations). I mean the available discovered main classes change depending on the indexing state of the debug adapter and also when you add new classes.

**Comment by MrcJkb** [comment]
Thanks for the input.
I like the idea of an event hook on the `dap` side. Maybe something that can be configured externally, e.g. by other plugins like `nvim-jdtls`.
That way users could define one or multiple triggers, or a timer, if needed.

Auto-detection of new main methods would be cool, but I'm not sure if it would have a negative performance impact in large projects. One solution could be a write hook that checks the outline of the current buffer for a `main` method (by calling `textDocument/documentSymbol`) and reloads the configurations if one is found and a configuration for it doesn't exist yet. 

I still have one week of holiday left, so I'll be glad to put some thought into it, too :)
But I'll need some time to browse through the nvim-dap code.

**Comment by mfussenegger** [comment]
There's also the option to move away from extending the configurations altogether to either codelens or some custom jdtls specific `run_main`, similar to how the test functions already work.

**Comment by MrcJkb** [comment]
> Another option would be to expose the function that returns the main class configurations. That would offer users the biggest flexibility

I like that idea. The project I'm testing this with has over 50 main methods. It would be great to be able to filter them (e.g. by open buffers) or to implement a fuzzy search.

**Comment by mfussenegger** [comment]
> > Another option would be to expose the function that returns the main class configurations. That would offer users the biggest flexibility
> 
> I like that idea. The project I'm testing this with has over 50 main methods. It would be great to be able to filter them (e.g. by open buffers) or to implement a fuzzy search.

Then I'd go with this. I think it is the simplest solution. `setup_dap()` would then no longer automatically add the configurations, instead users would have to call this new method manually. They can choose when to do so,  add post-processing if they choose to and decide whether they want to change `dap.configurations.java` with the result or use it directly in another way.


For the fuzzy search you could btw. override the `pick_one` / `pick_one_async` functions. See https://github.com/mfussenegger/nvim-jdtls/wiki/UI-Extensions

(In `dap` it is `require('dap.ui').pick_one = your_custom_picker` -   the `pick_one` of dap is the same as `pick_one_async` of jdtls)

**Comment by mfussenegger** [comment]
@MrcJkb Could you have a look at https://github.com/mfussenegger/nvim-jdtls/pull/84 ?

**Comment by mfussenegger** [comment]
Superseded by https://github.com/mfussenegger/nvim-jdtls/pull/84

Thank you again for pointing this out.

**Pull request closed without merging**
